
CREATE DATABASE IF NOT EXISTS atm_db CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE atm_db;
CREATE TABLE IF NOT EXISTS cliente (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cedula VARCHAR(20) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  pin CHAR(4) NOT NULL
);
CREATE TABLE IF NOT EXISTS cuenta (
  id INT AUTO_INCREMENT PRIMARY KEY,
  numero VARCHAR(20) NOT NULL UNIQUE,
  tipo ENUM('AHORROS','CORRIENTE') NOT NULL,
  saldo DECIMAL(12,2) NOT NULL DEFAULT 0,
  cliente_id INT NOT NULL,
  FOREIGN KEY (cliente_id) REFERENCES cliente(id)
);
CREATE TABLE IF NOT EXISTS transaccion (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  cuenta_id INT NOT NULL,
  tipo ENUM('DEPOSITO','RETIRO','TRANSFERENCIA') NOT NULL,
  monto DECIMAL(12,2) NOT NULL,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  meta VARCHAR(30) NULL,
  FOREIGN KEY (cuenta_id) REFERENCES cuenta(id)
);
INSERT INTO cliente (cedula, nombre, pin) VALUES
('10101010', 'Ana Pérez', '1234'),
('20202020', 'Luis Gómez', '5678')
ON DUPLICATE KEY UPDATE nombre=VALUES(nombre);
INSERT INTO cuenta (numero, tipo, saldo, cliente_id) VALUES
('1001', 'AHORROS', 500000.00, (SELECT id FROM cliente WHERE cedula='10101010')),
('1002', 'CORRIENTE', 150000.00, (SELECT id FROM cliente WHERE cedula='10101010')),
('2001', 'AHORROS', 250000.00, (SELECT id FROM cliente WHERE cedula='20202020'))
ON DUPLICATE KEY UPDATE saldo=VALUES(saldo);
